# Generated by Django 3.2.7 on 2021-09-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout_63530110', '0002_articulo_carritocompras_infoenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tipoelectrodomestico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
