# Generated by Django 3.2.7 on 2021-09-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout_63530110', '0004_auto_20210921_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoElectrodomestico',
        ),
    ]
